from pydantic import BaseModel, Field
from typing import Optional

class ArticleScript(BaseModel):
    """
    The output from a 'Reporter' agent. 
    It combines metadata from the source API with the AI-generated script.
    """
    # --- Metadata (Mapped from API Response) ---
    source_article_id: str = Field(..., description="The original 'id' from the articles API")
    source_name: str = Field(..., description="The publisher name (e.g., 'Gulfnews', 'Khaleejtimes')")
    source_url: str = Field(..., description="The original URL of the article")

    # --- AI Generated Content ---
    headline: str = Field(..., description="A punchy, broadcast-style headline generated by the AI")
    script_segment: str = Field(..., description="The summarized news script written for the ear (100-150 words)")
    
    # --- Editorial Judgment ---
    importance_score: int = Field(..., ge=1, le=10, description="News value score (1-10) based on categories and impact")
    reasoning: Optional[str] = Field(None, description="Why the agent assigned this score")