from pydantic import BaseModel, Field
from typing import List

class FinalBroadcastScript(BaseModel):
    """
    The final compiled script generated by the Chief Editor.
    """
    full_script: str = Field(..., description="The complete broadcast script with transitions")
    estimated_duration_minutes: float = Field(..., description="Estimated read time")
    
    # List of IDs used in the final cut (to track what actually made it to air)
    included_article_ids: List[str] = Field(default_factory=list)